Deployments:
  - Group1:
    - name: list-team
      image: v3
      namespace: development
      flyway: false
    - name: list-team
      image: v2
      namespace: staging
      flyway: false
  
  - Group-2:
    - name: my-service
      image: v3
      namespace: development
      flyway: true
    - name: my-service
      image: v3
      namespace: staging
      flyway: true
 
  - Group-3:
    - name: my-service
      image: v1
      namespace: slack-deployment
      flyway: true
  