groups:
  -
    - name: list-team
      image: v3
      namespace: development
      flyway: false
    - name: list-team
      image: v2
      namespace: staging
      flyway: false
    - name: list-team
      image: v2
      namespace: sit
      flyway: false
    - name: list-team
      image: v1
      namespace: slack-deployment
      flyway: true
  -
    - name: my-service
      image: v3
      namespace: development
      flyway: true
    - name: my-service
      image: v2
      namespace: staging
      flyway: true
    - name: my-service
      image: v2
      namespace: sit
      flyway: true
 
  -
    - name: my-service
      image: v1
      namespace: slack-deployment
      flyway: true
    - name: my-service
      image: v1
      namespace: slack-deployment
      flyway: true