Deployments:
  - databa:
    - name: list-team
      image: v3
      namespace: development
      flyway: false
    - name: list-team
      image: v2
      namespace: staging
      flyway: false
  
  - backend:
    - name: my-service
      image: v3
      namespace: development
      flyway: true
    - name: my-service
      image: v3
      namespace: staging
      flyway: true
 
  - frontend:
    - name: my-service
      image: v2
      namespace: development
      flyway: false
    - name: my-service
      image: v1
      namespace: slack-deployment
      flyway: true
  