mode: 'parallel'
deployments:
  - service: list-team
    image_tag: v3
    namespace: development
    flyway: false
  - service: list-team
    image_tag: v2
    namespace: staging
    flyway: false
  - service: my-service
    image_tag: v2
    namespace: staging
    flyway: true
  - service: my-service
    image_tag: v2
    namespace: development
    flyway: true