deployments:
  - service: list-team
    version: v3
    namespace: development
    flyway: false
  - service: list-team
    version: v2
    namespace: staging
    flyway: false
  - service: my-service
    version: v2
    namespace: staging
    flyway: true
  - service: my-service
    version: v2
    namespace: development
    flyway: true