#!/bin/bash

services=(
  "service1"
  "service2"
  "service3"
)

output=workflow.yaml

cat <<EOF > $output
# This file is auto-generated by generate-sequential-jobs.sh
name: Sequential Jobs Workflow
on: [push]
jobs:
EOF
i=0
for service in "${services[@]}"; do
  svc="${services[$i]}"
  prev_index=$((i - 1))
  prev_svc="${services[$prev_index]}"

  echo "    deploy-${svc}:" >> $output
  echo "        runs-on: ubuntu-latest" >> $output 
  if [[ $i -eq 0 ]]; then
    echo "        needs: []" >> $output
  else
    echo "        needs: deploy-${prev_svc}" >> $output
  fi
  cat <<EOF >> $output
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - name: Deploy ${svc}
            run: echo "Deploying ${svc}..."
EOF
  i=$((i + 1))
done
echo "Workflow file generated: $output"