# Default values for postgres Helm chart.

replicaCount: 1

image:
  repository: kishorechellaboina/postgres
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  name: postgres
  port: 80
  targetPort: 8080

containerPort: 8080

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
- name: "ENVIRONMENT"
  value: "development"
  
ingress:
  enabled: true
  className: "gce"
  annotations: {}
  hosts:
    - host: postgres-developement.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

nodeSelector: {}

tolerations: []

affinity: {}