# Default values for postgres Helm chart.

replicaCount: 1

image:
  repository: kishorechellaboina/list-team
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  name: postgres
  port: 80
  targetPort: 8080

containerPort: 8080

resources:
  limits:
    cpu: 150m
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 128Mi

env:
- name: "ENVIRONMENT"
  value: "development"
  

nodeSelector: {}

tolerations: []

affinity: {}