name: CD - Deploy Helm Charts to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: perceptive-day-462306-t3
  GKE_CLUSTER: my-cluster-1
  GKE_ZONE: us-central1
  # HELM_CHART_PATH: ./${{ matrix.service }}
  IMAGE_TAG: v1


jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read versions.txt and create matrix
        id: set-matrix
        run: |
          matrix=$(awk '{printf "{\"service\":\"%s\",\"version\":\"%s\",\"namespace\":\"%s\"},", $1, $2, $3}' deployment.txt | sed 's/,$//')
          echo "matrix={\"include\":[${matrix}]}" >> $GITHUB_OUTPUT

  deploy:
    needs: generate-matrix
    name: Deploy ${{ matrix.service }} Helm Charts into GKE  ${{ matrix.namespace }} namespace
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
    env:
      namespace: ${{ matrix.namespace }}
      service: ${{ matrix.service }}
      version: ${{ matrix.version }}
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true


    - name: Install gke-gcloud-auth-plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin --quiet

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }}

    - name: Set up Helm
      uses: azure/setup-helm@v3

    # - name: Create namespace if not exists
    #   run: |
    #     kubectl get namespace  || kubectl create namespace my-namespace

    - name: Build Helm chart
      run: |
        ls -la
        ls -la ./$service
        helm lint ./${{ matrix.service }}
        helm dependency update ./${{ matrix.service }}
        helm package ./${{ matrix.service }} --destination ./helm-packages

    - name: Deploy to GKE using Helm
      run: |
        if [ -f ./${{ matrix.service }}/values-${{ matrix.namespace }}.yaml ]; then
          helm upgrade --install ${{ matrix.service }} ./helm-packages/${{ matrix.service }}-*.tgz \
            --namespace ${{ matrix.namespace }} \
            --set image.tag=${{ matrix.version }} \
            -f ./${{ matrix.service }}/values.yaml \
            -f ./${{ matrix.service }}/values-${{ matrix.namespace }}.yaml
        else
          helm upgrade --install ${{ matrix.service }} ./helm-packages/${{ matrix.service }}-*.tgz \
            --namespace ${{ matrix.namespace }} \
            --set image.tag=${{ matrix.version }} \
            -f ./${{ matrix.service }}/values.yaml
        fi
