name: CD - Deploy Helm Charts to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: perceptive-day-462306-t3
  GKE_CLUSTER: my-cluster-1
  GKE_ZONE: us-central1
  HELM_CHART_PATH: ./list-team

jobs:
  deploy:
    runs-on: ubuntu-latest

    name: Build and Deploy Helm Charts to GKE
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true


    - name: Install gke-gcloud-auth-plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin --quiet

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }}

    - name: Set up Helm
      uses: azure/setup-helm@v3

    # - name: Create namespace if not exists
    #   run: |
    #     kubectl get namespace  || kubectl create namespace my-namespace

    - name: Build Helm chart
      run: |
        ls -la
        ls -la ./list-team
        helm lint ./list-team
        helm dependency update ./list-team
        helm package ./list-team --destination ./helm-packages

    - name: Deploy to GKE using Helm
      run: |
        helm upgrade --install list-team ./helm-packages/list-team-*.tgz \
          --namespace development
