# .github/workflows/main.yaml
name: Seqential or Parallel Deployments
# description: Deploy services either sequentially or in parallel based on the configuration in services.yaml

on:
  push:
    branches:
      - main

jobs:
  read-services:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.read.outputs.matrix }}
      mode: ${{ steps.read.outputs.mode }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install yq and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          sudo snap install yq

      - name: Read services
        id: read
        run: |
          echo "Reading services from deployments.yaml"
          matrix=$(yq -o=json '.deployments' deployments.yaml | jq -c)
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

          mode=$(yq -r '.mode' deployments.yaml)
          echo "mode=$mode" >> $GITHUB_OUTPUT
          echo "$matrix"
          echo $mode

  deployments-parallel:
    needs: read-services
    if: ${{ needs.read-services.outputs.mode == 'parallel' }}
    strategy:
      matrix:
        service: ${{ fromJson(needs.read-services.outputs.matrix) }}
    uses: kishore3github/helm-deployments/.github/workflows/reusable_cd.yaml@main
    with:
      service: ${{ matrix.service.name }}
      namespace: ${{ matrix.service.namespace }}
      image_tag: ${{ matrix.service.image_tag }}
      flyway: ${{ matrix.service.flyway }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}



  deployments-sequential:
    needs: read-services
    if: ${{ needs.read-services.outputs.mode == 'sequential' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Deploy services sequentially
        env:
          MATRIX: ${{ needs.read-services.outputs.matrix }}
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          echo "Deploying services sequentially"
          echo "$MATRIX" | jq -c '.[]' | while read service; do
            name=$(echo $service | jq -r '.name')
            namespace=$(echo $service | jq -r '.namespace')
            image_tag=$(echo $service | jq -r '.image_tag')
            flyway=$(echo $service | jq -r '.flyway')
            if [ "$name" == "null" ] || [ "$namespace" == "null" ] || [ "$image_tag" == "null" ]; then
              echo "Skipping service with missing fields: $service"
              continue
            fi
            echo "Processing service: $name"

            echo "Triggering deployment for $name in namespace $namespace with image tag $image_tag"
            gh workflow run reusable_cd.yaml -f service="$name" -f namespace="$namespace" -f image_tag="$image_tag" -f flyway="$flyway"

            echo "Waiting for deployment of $name to complete..."
            # Wait a few seconds to ensure the workflow is registered
            sleep 20

            # Get the latest run ID for the workflow
            run_id=$(gh run list --workflow=reusable_cd.yaml --limit=1 --json databaseId --jq '.[0].databaseId')

            # Wait for that run to complete
            gh run watch "$run_id"

            echo "Deployment of $name completed."
            sleep 10
          done

